// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBJPRt6Lfnzm-x-AgwdhMhM-5m7csQGxw',
    appId: '1:319202679340:web:ab6497b4cc0d8c17c18f89',
    messagingSenderId: '319202679340',
    projectId: 'login-ff001',
    authDomain: 'login-ff001.firebaseapp.com',
    storageBucket: 'login-ff001.appspot.com',
    measurementId: 'G-NJD3PQRMNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDJMIFyE2f7l1FEHa4xlbyF2_f1ofeZMo',
    appId: '1:319202679340:android:2e06d0f30bc0b71fc18f89',
    messagingSenderId: '319202679340',
    projectId: 'login-ff001',
    storageBucket: 'login-ff001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYcb5Ed6Hjw_Osan0u-PXJ1LUBTqz3R3I',
    appId: '1:319202679340:ios:14261e0112775b1ec18f89',
    messagingSenderId: '319202679340',
    projectId: 'login-ff001',
    storageBucket: 'login-ff001.appspot.com',
    iosBundleId: 'com.example.contactBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBJPRt6Lfnzm-x-AgwdhMhM-5m7csQGxw',
    appId: '1:319202679340:web:46ef912f4485409ec18f89',
    messagingSenderId: '319202679340',
    projectId: 'login-ff001',
    authDomain: 'login-ff001.firebaseapp.com',
    storageBucket: 'login-ff001.appspot.com',
    measurementId: 'G-T6CTL2DC04',
  );
}
